server:
  port:
    8082
security:
  jwt:
    subscription-key: Q3JvJDUtNmFtMy1NYTdjaE1AazFuNg==
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usuario
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
---
#spring:
#  datasource:
#    url: jdbc:h2:mem:user
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect